name: 'Manage Repo Tags'

on:
  push:
    branches:
      - master
    paths:
      - .tags

jobs:
  create-tags:
    if: ${{ github.repository == 'kubernetes/cloud-provider-gcp' }}
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Checkout all tags & branches
          fetch-tags: true
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: tools/create-repo-tags
